### ISSUE TITLE
LegacyApplication missing?

### ISSUE THREAD

**Issue by gbivins** [phr00t/jmonkeyengine-virtual-reality#12]
I'm trying to use build/run the demo and out of the box the demo.zip failed.
>java -jar JMonkeyVR.jar
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.IncompatibleClassChangeError: Implementing class
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)

So I then attempted to download the source and build it myself but the code doesn't compile because it's missing LegacyApplication in jme-core. 
Any suggestions to resolve this? I'm familiar with scenegraph API's and VR API's but this seems more fundamental. Is there a specific version of jme-core I should use other than the one included in the zip:
https://github.com/phr00t/jMonkeyVR/archive/master.zip

**Comment by gbivins** [comment]
Maybe I'm answering my own question...I see that this requires this build jme:
https://github.com/phr00t/jmonkeyengine

I'll try that

**Comment by gbivins** [comment]
Victory!
After referencing phr00t/jme I only needed to change CONSTRUCT_WITH_OSVR to false since I'm using vive!
AWESOME! Great work here!
