### ISSUE TITLE
AssetNotFoundException spheremap

### ISSUE THREAD

**Issue by Wound** [phr00t/jmonkeyengine-virtual-reality#13]
Hi. I have setup the jMonkeyVR demo on Windows10 x64 using your current JMonkey-Build and copied the assets from the JMonkeyVR-Git to the demo folder. This solved an AssetNotFoundException with "Textures/happy.png". But now I persistently get the following error:

`Jan 10, 2017 7:58:54 PM jmevr.app.VRApplication handleError
SCHWERWIEGEND: Uncaught exception thrown in Thread[main,5,main]
com.jme3.asset.AssetNotFoundException: Textures/Sky/Bright/spheremap.png (Flipped)
        at com.jme3.asset.DesktopAssetManager.loadAsset(DesktopAssetManager.java:370)
        at com.jme3.asset.DesktopAssetManager.loadTexture(DesktopAssetManager.java:390)
        at com.jme3.util.SkyFactory.createSky(SkyFactory.java:292)
        at jmevr.TestjMonkeyVR.initTestScene(TestjMonkeyVR.java:85)
        at jmevr.TestjMonkeyVR.simpleInitApp(TestjMonkeyVR.java:74)
        at jmevr.app.VRApplication.initialize(VRApplication.java:1094)
        at com.jme3.system.lwjgl.LwjglWindow.initInThread(LwjglWindow.java:346)
        at com.jme3.system.lwjgl.LwjglWindow.run(LwjglWindow.java:447)
        at com.jme3.system.lwjgl.LwjglWindow.create(LwjglWindow.java:297)
        at jmevr.app.VRApplication.start(VRApplication.java:629)
        at jmevr.app.VRApplication.start(VRApplication.java:604)
        at jmevr.TestjMonkeyVR.main(TestjMonkeyVR.java:62)`

But the file actually *is* located at the expected position at Textures\Sky\Bright\spheremap.png relative to the starting directory. The PNG opens nicely on double click.

**Comment by phr00t** [comment]
Weird... maybe try moving the spheremap.png file next to happy.png? If it can read happy.png, it should be able to find spheremap.png...

**Comment by Wound** [comment]
Thanks for the quick response! I really appreciate that.
Unfortunately that did not help (wouldn't have expected that anyway)
What actually worked, was packing the asset directories into the JMonkeyVR.jar. Strange, isn't it?

But now, my Vive is not recognized. The original contents of the demo.zip fired up SteamVR and crashed shortly afterwards. =>
'INFORMATION: Running on jMonkeyEngine 3.1-5553
 * Branch: master
 * Git Hash: 517aeb5
 * Build Date: 2015-11-16
OpenVR Compositor initialized OK.
Jan 10, 2017 8:31:24 PM com.jme3.app.Application handleError
SCHWERWIEGEND: Uncaught exception thrown in Thread[jME3 Main,5,main]
java.lang.Error: Invalid memory access
        at jopenvr.JOpenVRLibrary.VR_IVRSystem_PollNextEvent(Native Method)
        at jmevr.input.OpenVR.updatePose(OpenVR.java:260)
        at jmevr.util.OpenVRViewManager.update(OpenVRViewManager.java:245)
        at jmevr.util.OpenVRViewManager.initialize(OpenVRViewManager.java:168)
        at jmevr.app.VRApplication.initialize(VRApplication.java:537)
        at com.jme3.system.lwjgl.LwjglWindow.initInThread(LwjglWindow.java:310)
        at com.jme3.system.lwjgl.LwjglWindow.run(LwjglWindow.java:408)
        at java.lang.Thread.run(Unknown Source)'

Just like issue #4

**Comment by phr00t** [comment]
Are you packing in all of the OpenVR libraries too..? The JMonkeyVR.jar file in the root directory should already have all of this, so you just need to add JAR. Are you trying to build JMonkeyVR.JAR yourself?

**Comment by Wound** [comment]
No. I am currently trying to use the current JMonkeyVR.jar with included assets. I have replaced all jars in the lib directory (not in jar) with the jars from your current JMonkey-Build

https://github.com/phr00t/jmonkeyengine/tree/master/dist/lib

I have also placed the lwjgl64.dll to the working directory and jna-4.2.1.jar into the lib directory.

ANd I had a look into the MANIFEST.MF in the main jar.
The following classpath is defined in there.
'lib/jnaerator-runtime-0.12.jar lib/lwjgl-3.0.0.jar lib/lwj
 gl-3.0.0-natives.jar lib/jinput-platform-natives-linux.jar lib/j-ogg-
 all.jar lib/jinput-platform-natives-osx.jar lib/jinput-platform-nativ
 es-windows.jar lib/jinput.jar lib/jme3-core.jar lib/jme3-desktop.jar 
 lib/jme3-effects.jar lib/vecmath.jar lib/jme3-lwjgl3.jar lib/jna-plat
 form-4.2.2.jar lib/jna-4.2.2.jar lib/assets.jar'

I see a lot of different version numbers there than in the lib. And not all of the classpath entries exist in any version. I am a little confused, what is actually required and what not.

With this in place, the application starts, shows me the JMonkey-Config dialog and then runs on my monitor, not on my headset.

**Comment by phr00t** [comment]
Wait a minute... demo.zip? Ugh, I should remove that. demo.zip is soooo old, I doubt anything would work from it.

**Comment by phr00t** [comment]
You might be able to just run the JMonkeyVR.JAR file to test, or take the sample application, compile that with the JMonkeyVR.JAR as an included library.

**Comment by Wound** [comment]
Well the demo.zip contents at least made my SteamVR jump, even though it crashed afterwards.

At the moment the dependencies in the current JMonkeyVR.jar seem to be inconsistent with the libs in the JME. From that point of view, I am not sure, whether the build would succeed. Where do I get jna-4.2.2.jar from for example? I think I would have to setup Netbeans to retrieve all the dependencies.

Could you probably export a new demo dist, with everything where it belongs?

**Comment by Wound** [comment]
I do not have Netbeans installed at the moment. Some general dependency management config like gradle, sbt or maven would help to import the project into any IDE of choice

**Comment by Wound** [comment]
I've tried to simply run the JMonkeyVR.jar by the way, but even though the main class is in there at the expected position, jemvr/... I get a main "class not found" error

**Comment by phr00t** [comment]
demo.zip will likely start OpenVR, but it is probably using pre-v1.0 libraries. You can get jna-4.2.2.jar from here: http://central.maven.org/maven2/net/java/dev/jna/jna/4.2.2/jna-4.2.2.jar

I don't particularly have time to setup another demo... this library does work with my jMonkeyEngine build, OpenVR & OSVR. However, it is "feature frozen", as I've moved on to Unity. I'm only keeping it maintained for my games.

You are probably getting main "class not found" errors because it needs all of the jme3 libraries from my jMonkeyEngine build.

Setting up gradle/maven etc. is issue #3
